---
- name: Demo playbook 
  hosts: all 
  tasks:
    - name: Print hello 
      debug:
        msg: "Hello world"

    - name: Print facts
      debug:
        msg: "{{ ansible_facts }}"

    - name: Print host name 
      debug:
        msg: "{{ ansible_hostname }}"

    - setup:

    - debug: var=hostvars[inventory_hostname]

    - shell: curl https://ifconfig.me
      register: ifout

    - debug: var=ifout

    - shell: curl 'https://api.ipify.org?format=json'
     register: ifout1

    - debug: var=ifout1
    
    - name: Create a dummy file 
      copy:
        content: "hey, I am from demo, creating a file for you"
        dest: /tmp/demo
