---
- name: Demo playbook 
  hosts: all 
  tasks:
    - name: Print hello 
      debug:
        msg: "Hello world:

    - name: Print facts
      debug:
        msg: "{{ ansible_facts }}"

    - name: Print host name 
      debug:
        msg: "{{ ansible_hostname }}"

    - name: Print variable 
      debug:
        msg: "{{ test_var }}"
      when: test_var is defined 
