---
- name: Demo playbook 
  hosts: all 
  tasks:

    - name: Print variable 
      debug:
        msg: "{{ my_var | default([]) }}"

        
    - name: Print secret 
      debug:
        msg: "{{ my_secret | default([]) }}"
