---
- name: Demo playbook for vault 
  hosts: localhost 
  tasks:

    - debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/data/test token=root url=http://vault-default.apps.cluster-gj9f5.gj9f5.sandbox1545.opentlc.com') }}"
