---
- name: Demo playbook for vault 
  hosts: localhost 
  tasks:
    - name: install hvac pip package
      become: yes
      become_method: sudo
      pip:
        name: hvac
        state: present
      
        
    - debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/data/test') }}"
