---
- name: Demo playbook for vault 
  hosts: localhost 
  tasks:
    - name: install hvac pip package
      become: yes
      become_method: sudo
      pip:
        name: hvac
        state: present
      
        
    - name: Print the KV 
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/data/test') }}"
    - name: Print value 
      debug:        
        msg: "{{ lookup('hashi_vault', 'secret=secret/data/test:what') }}"
        #msg: "{{ lookup('hashi_vault', 'secret=secret/data/test token=root url=http://vault-default.apps.cluster-gj9f5.gj9f5.sandbox1545.opentlc.com') }}"
