---
- name: Demo playbook for vault 
  hosts: localhost 
  tasks:

    - name: Print hello 
      debug:
        msg: "Hello from playbook with secrets"

    - name: install hvac pip package
      become: yes
      become_method: sudo
      pip:
        name: hvac
        state: present
      
    - name: Print the KV from vault
      debug:
        msg: "{{ lookup('hashi_vault', 'secret=secret/data/test') }}"
        
    - name: Print the secret value only 
      debug:        
        msg: "{{ lookup('hashi_vault', 'secret=secret/data/test:what') }}"

    - name: Set Stats  
      set_stats:
        data:
          my_var: "not a secret"    
          my_secret: "{{ lookup('hashi_vault', 'secret=secret/data/test:what') }}"
